### PR TITLE
Updating base Amazon AMI to Sep-2016 release

### PR DESCRIPTION
**Pull request by RoryH**

### CODE REVIEW

**Comment by RoryH** [comment]
@gheine @kevinoriordan

**Comment by gheine** [comment]
👍

**Comment by grahamar** [comment]
@RoryH @gheine just an FYI, there's no real need to update the base AMI anymore, as the nova setup command run on startup does a yum update. Amazon made a change a while back that the yum update brings all updates incrementally that are rolled up into their latest AMIs.

As you can see from their release notes: https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes/

> To upgrade to Amazon Linux AMI 2016.09 from 2011.09 or later, run sudo yum clean all followed by sudo yum update. When the upgrade is complete, reboot your instance.
> 
> Remember that the Amazon Linux AMI repository structure is configured to deliver a continuous flow of updates that allow you to roll from one version of the Amazon Linux AMI to the next. Please consult our lock-on-launch FAQ for a discussion of how you can lock an instance (either a new launch or one already running) to a particular version of the Amazon Linux AMI repositories.

**Comment by RoryH** [comment]
@grahamar I presume it makes everything a bit more efficient if we have the pre-rolled latest AMI, as opposed to have to update every time we spin up a new instance?

**Comment by gheine** [comment]
Also, there's the fact that the upgrade requires a reboot...

**Comment by grahamar** [comment]
@RoryH yes definitely, was just making the point that we're already up-to-date, and also trying to keep the number of AMI updates to a minimum as people are less likely to update if there's constant new versions.

@gheine depends on the update, most don't actually need them. Do you reboot your machine after a `pip install -U`? 😄

**Pull request merged**
